#!/usr/bin/env bash
# Configuring a new server

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginxsites-available/reitu-r.tech.conf
echo "Hello World" > /var/html/index.html
sudo service nginx restart
