#!/usr/bin/env bash
# install haproxy and config 2 server
apt-get update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 25076-web-01 3.236.209.52:80 check\n\tserver 25076-web-02 3.234.241.189:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
