#!/usr/bin/env bash
#This Script is displaying "Best School" 10 times
var="Best School"
i=1
while [ $i -le 10 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else	
		echo "$var"
	fi
	((i++))
done
