#!/usr/bin/env bash
#This Script is displaying numbers from 1 to 20 using case statement
i=1
while [ $i -le 20 ]
do
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "Bad luck from Italy"
		;;
	*)
		echo $i
	esac
	((i++))
done
